apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgATqTd33NJAxYm6Ly0o4/31mJ3wJZdAK7jnXT9hMl2z6/tf0lU9PzfpfJtjZBt8EKHXAz+UvTK9+PGJcAfpfYzsrZTg1FwKQCuBRiajEjegrjSlMAxy13K1JFSz9y7RDM859ti9jeXOmz1pXBpE7xHIUssdcxDaIVrb9oS7+tIrx/tQ8fgYqgYsbfp2xgP2z+8zN1/jPRNp1g+PmUblb4s8d2hAuHiLgqlHI4Sgvr3Ah61fdO7grQ8iIkGZBLBEe8M7QUfVNRExEFpxocSa2mDaYWoeM/gvTWUPVuY61Dj8+Z6PElZg4pRC/krSmeCmkbDHOInfNf39311/OVGIXe9SJJX4FFUcXJxOwVG332pIanYGrXB61QFtkVuAfSSlFqBh/yhoKvEW9nIyNayOn0oOyUsU0GnBNjNZ98eFDTpyu5Gx0O1NN1gBOQGhPrtHZp9Vpqg0oZyrTZX+VFm/F2HnedtN2iB/4ELjNhsztW370u/GAzH85eXYKd54HxBNA3OjIDtyHpMI9CLFZ/fpdUk9JmoD7qMjkPP+GVqrD73rK8CbC5hNsHQz71McD7xTtG/hi/+tx9GMopg4xwbILKomhLxwSIPnbb24EDfkWO5rquuop4GLVlHyMS2cmSTPYr8/DIAy6Bxxu49aDPVkTsNZRx3kYdVw9i4Nina8bY/ynqqIoc1rqQbgba51JxABslWtx26LWtt8II+gOYljtwr/apXfxQTC76Fmj3z1yY6luXJJM9JsLDWt
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

